### ISSUE TITLE
AttributeError: 'float' object has no attribute 'decode'

### ISSUE THREAD

**Issue by slobLX** [lpty/nlp_base#15]
So sorry to bother you again...

when I use "train()"

the error occur:
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.173 seconds.
Prefix dict has been built succesfully.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "interrogative/api.py", line 17, in train
    model.train()
  File "interrogative/model.py", line 76, in train
    self.initialize_model()
  File "interrogative/model.py", line 31, in initialize_model
    train, label = self.corpus.generator()
  File "interrogative/corpus.py", line 62, in generator
    corpus = cls.read_corpus_from_file(corpus_path)
  File "interrogative/corpus.py", line 34, in perform_word_segment
    tokenizer = jieba.Tokenizer()
  File "/home1/liuxin/anaconda3/envs/py27/lib/python2.7/site-packages/pandas/core/series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer
  File "interrogative/corpus.py", line 34, in <lambda>
    tokenizer = jieba.Tokenizer()
  File "/home1/liuxin/.local/lib/python2.7/site-packages/jieba/__init__.py", line 282, in cut
    sentence = strdecode(sentence)
  File "/home1/liuxin/.local/lib/python2.7/site-packages/jieba/_compat.py", line 37, in strdecode
    sentence = sentence.decode('utf-8')
AttributeError: 'float' object has no attribute 'decode'

**Comment by xyzindeed** [comment]
you can just move decode('utf-8') directly. Beacuse in python 3, it was unicode str.

**Comment by fengchangmin666** [comment]
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 0.906 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "C:/Users/Lenovo/Desktop/interrogative/manage.py", line 3, in <module>
    train()
  File "C:\Users\Lenovo\Desktop\interrogative\src\api.py", line 17, in train
    model.train()
  File "C:\Users\Lenovo\Desktop\interrogative\src\model.py", line 81, in train
    _, best_param, best_iter_round = self.model_param_select()
  File "C:\Users\Lenovo\Desktop\interrogative\src\model.py", line 67, in model_param_select
    early_stopping_rounds=self.early_stopping_rounds)  # stop when metrics not get better
  File "D:\python project\venv\lib\site-packages\xgboost\training.py", line 445, in cv
    fold.update(i, obj)
  File "D:\python project\venv\lib\site-packages\xgboost\training.py", line 230, in update
    self.bst.update(self.dtrain, iteration, fobj)
  File "D:\python project\venv\lib\site-packages\xgboost\core.py", line 1109, in update
    dtrain.handle))
  File "D:\python project\venv\lib\site-packages\xgboost\core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for silent expect boolean but value='91'

**Comment by fengchangmin666** [comment]
我用的是：demjson.encode(text, encoding='utf-8')
