### ISSUE TITLE
打扰了这个xgboost.core.XGBoostError: Invalid Parameter format for silent expect boolean but value='91'怎么改呀，谢谢

### ISSUE THREAD

**Issue by fengchangmin666** [lpty/nlp_base#17]
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 0.906 seconds.
Prefix dict has been built succesfully.
Traceback (most recent call last):
File "C:/Users/Lenovo/Desktop/interrogative/manage.py", line 3, in 
train()
File "C:\Users\Lenovo\Desktop\interrogative\src\api.py", line 17, in train
model.train()
File "C:\Users\Lenovo\Desktop\interrogative\src\model.py", line 81, in train
_, best_param, best_iter_round = self.model_param_select()
File "C:\Users\Lenovo\Desktop\interrogative\src\model.py", line 67, in model_param_select
early_stopping_rounds=self.early_stopping_rounds) # stop when metrics not get better
File "D:\python project\venv\lib\site-packages\xgboost\training.py", line 445, in cv
fold.update(i, obj)
File "D:\python project\venv\lib\site-packages\xgboost\training.py", line 230, in update
self.bst.update(self.dtrain, iteration, fobj)
File "D:\python project\venv\lib\site-packages\xgboost\core.py", line 1109, in update
dtrain.handle))
File "D:\python project\venv\lib\site-packages\xgboost\core.py", line 176, in _check_call
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for silent expect boolean but value='91'

**Comment by lxinghai007** [comment]
我也遇到同样的问题，谁知道如何解决？
